# These are supported funding model platforms

buy_me_a_coffee: mmr710 # Replace 'mmr710' with your actual Buy Me A Coffee username if different
custom: ["https://tronscan.org/#/address/TG2GZhZHg5N892M3nEzRdqpbDSVT2BffwN"] # Links to your USDT TRX address on Tronscan
