# These are supported funding model platforms

custom: ["https://t.me/+SGmmExdMHTQ3OWVk"] # Replace with a buymeacoffee or other link if created
# Add a note about the USDT donation in the repo instead since FUNDING.yml doesn't support raw crypto addresses elegantly unless linked to a page.
